### ISSUE TITLE
Device with no camera and dummy videos

### ISSUE THREAD

**Issue by mujehoxe** [Genymobile/genymotion-device-web-player#15]
Hi is there a way to emulate a device without a front or back camera just to for testing a fallback functionality? this also concerns the desktop emulator. Or an option to provide a video that keeps replaying would be very helpful.

**Comment by jmaneyrol69** [comment]
Hi @mujehoxe,

Sorry for the late answer. This discussion board is for our web player Java SDK only. Please use our Genymotion generic discussion board at https://github.com/orgs/Genymobile/discussions instead.

Thank you.
Best regards
